export const BACKEND_BASE_URL = process.env.REACT_APP_BACKEND_URL;

export const SUPER_SECRET_ENCRYPT_KEY = process.env.REACT_APP_SUPER_SECRET_ENCRYPT_KEY;

export const AUTH_TOKEN_KEY = process.env.REACT_APP_AUTH_TOKEN_KEY;
export const AUTH_COOKIE_NAME = process.env.REACT_APP_AUTH_COOKIE_NAME;
